/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import Clases.OperacionesData;
import Clases.Producto;
import Clases.Usuario;
import Controladores.PlaceHolder;
import Controladores.ControladorData;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class frmAgregarProductoYusuario extends javax.swing.JFrame {

    private DefaultTableModel dtmTablaDeProductos;
    private DefaultTableModel dtmTablaDeUsuarios;
    Object[][] data = {};
    String headerProducto[] = {"CODIGO DE PRODUCTO", "ESTADO", "CANTIDAD", "CATEGORIA", "NOMBRE DE PRODUCTO", "PRECIO UNITARIO",
        "ALMACEN", "DESTINO", "FECHA DE REGISTRO", "FECHA DE ENTREGA", "CODIGO DE USUARIO", "PRECIO TOTAL"
    };
    String headerUsuario[] = {"CODIGO DE USUARIO", "NOMBRE DE USUARIO", "TELEFONO"};
    private OperacionesData od;
    private ControladorData cd;
    /*LISTAS Y ENCONTRADOS*/
    LinkedList<Producto> listaDeProductos;
    LinkedHashSet<Usuario> listaDeUsuario;
    Producto productoEncontrado;
    Usuario usuarioEncontrado;

    public frmAgregarProductoYusuario() {
        initComponents();
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        establecerPlaceHolders();
        escalarImagen();
        cd = new ControladorData();
        listaDeProductos = cd.instanciarListaProducto();
        listaDeUsuario = cd.instanciarListaUsuario();
        /*OPERACIONES TABLA*/
 /*TBL DE PRODUCTO*/
        dtmTablaDeProductos = new DefaultTableModel();
        dtmTablaDeProductos.setDataVector(data, headerProducto);
        jtblProducto.setModel(dtmTablaDeProductos);
        /*TBL DE USUARIOS*/
        dtmTablaDeUsuarios = new DefaultTableModel();
        dtmTablaDeUsuarios.setDataVector(data, headerUsuario);
        jtblUsuario.setModel(dtmTablaDeUsuarios);
    }

    private void escalarImagen() {
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelUsuario, "src/Imagenes/imgCambiarUsuario.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelProducto, "src/Imagenes/imgProducto.jpg");
    }

    private void establecerPlaceHolders() {
        PlaceHolder phNombreUsuario = new PlaceHolder("Ingrese el Usuario", jtxtNombreDeUsuario);
        PlaceHolder phCodigoUsuario = new PlaceHolder("Ingrese el codigo de usuario", jtxtCodigoDeUsuario);
        PlaceHolder phTelefonoUsuario = new PlaceHolder("Ingrese el numero telefonico", jtxtNumeroTelefonico);
        PlaceHolder phCodigoProducto = new PlaceHolder("Ingrese el codigo de producto", jtxtCodigoDeProducto);
        PlaceHolder phNombreProducto = new PlaceHolder("Ingrese el nombre del producto", jtxtNombreDeProducto);
        PlaceHolder phCantidaDeProducto = new PlaceHolder("Ingrese la cantidad de producto", jtxtCantidaDeProducto);
        PlaceHolder phPrecio = new PlaceHolder("Ingrese el precio del producto", jtxtPrecioDelProducto);
        PlaceHolder phDestino = new PlaceHolder("Ingrese el destino del producto", jtxtDestinoDelProducto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbgOrientacion = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jbtnInicio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtNumeroTelefonico = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jtxtNombreDeUsuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jtxtCodigoDeUsuario = new javax.swing.JTextField();
        jbtnAgregarProducto = new javax.swing.JButton();
        jlabelProducto = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jtxtNombreDeProducto = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jtxtCantidaDeProducto = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jtxtCodigoDeProducto = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jtxtPrecioDelProducto = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jtxtDestinoDelProducto = new javax.swing.JTextField();
        jcFechaDeEntregaDeProducto = new com.toedter.calendar.JDateChooser();
        jcFechaDeRegistroDeProducto = new com.toedter.calendar.JDateChooser();
        jcbxAlmacen = new javax.swing.JComboBox<>();
        jcbxEstado = new javax.swing.JComboBox<>();
        jcbxCategoria = new javax.swing.JComboBox<>();
        jbtnCambiarUsuario = new javax.swing.JButton();
        jlabelUsuario = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblProducto = new javax.swing.JTable();
        jbtnEliminar = new javax.swing.JButton();
        jbtnActualizar = new javax.swing.JButton();
        jbtnRestaurar = new javax.swing.JButton();
        jbtnConsultar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblUsuario = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jckbUsuario = new javax.swing.JCheckBox();
        jrbInicioAFIn = new javax.swing.JRadioButton();
        jckbProducto = new javax.swing.JCheckBox();
        jrbFinAInicio = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1640, 0, 50, -1));

        jbtnInicio.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 580, 180, 60));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AGREGAR USUARIO Y PRODUCTO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, 40));

        jPanel3.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "TELEFONO DEL USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNumeroTelefonico.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNumeroTelefonico.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNumeroTelefonico.setBorder(null);
        jPanel3.add(jtxtNumeroTelefonico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 390, 70));

        jPanel4.setBackground(new java.awt.Color(215, 215, 215));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NOMBRE DE USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreDeUsuario.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNombreDeUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNombreDeUsuario.setBorder(null);
        jPanel4.add(jtxtNombreDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 390, 70));

        jPanel5.setBackground(new java.awt.Color(215, 215, 215));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CODIGO DE USUARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCodigoDeUsuario.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCodigoDeUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCodigoDeUsuario.setBorder(null);
        jtxtCodigoDeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jtxtCodigoDeUsuarioMouseExited(evt);
            }
        });
        jPanel5.add(jtxtCodigoDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 390, 70));

        jbtnAgregarProducto.setBackground(new java.awt.Color(149, 16, 43));
        jbtnAgregarProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jbtnAgregarProducto.setText("GENERAR VENTA");
        jbtnAgregarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 200, 70));

        jlabelProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgProducto.jpg"))); // NOI18N
        jPanel2.add(jlabelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 220));

        jPanel6.setBackground(new java.awt.Color(215, 215, 215));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NOMBRE DEL PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNombreDeProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNombreDeProducto.setBorder(null);
        jPanel6.add(jtxtNombreDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 390, 70));

        jPanel8.setBackground(new java.awt.Color(215, 215, 215));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CANTIDAD DE PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCantidaDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCantidaDeProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCantidaDeProducto.setBorder(null);
        jPanel8.add(jtxtCantidaDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 390, 70));

        jPanel7.setBackground(new java.awt.Color(215, 215, 215));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CODIGO DE PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCodigoDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCodigoDeProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCodigoDeProducto.setBorder(null);
        jPanel7.add(jtxtCodigoDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 390, 70));

        jPanel11.setBackground(new java.awt.Color(215, 215, 215));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "PRECIO DEL PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrecioDelProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtPrecioDelProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtPrecioDelProducto.setBorder(null);
        jPanel11.add(jtxtPrecioDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 390, 70));

        jPanel9.setBackground(new java.awt.Color(215, 215, 215));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "DESTINO DEL PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtDestinoDelProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtDestinoDelProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtDestinoDelProducto.setBorder(null);
        jPanel9.add(jtxtDestinoDelProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 390, 70));

        jcFechaDeEntregaDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jcFechaDeEntregaDeProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha de Entrega", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel2.add(jcFechaDeEntregaDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 390, 90));

        jcFechaDeRegistroDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jcFechaDeRegistroDeProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Fecha De Registro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jPanel2.add(jcFechaDeRegistroDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 390, 90));

        jcbxAlmacen.setBackground(new java.awt.Color(215, 215, 215));
        jcbxAlmacen.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbxAlmacen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almacen Centro", "Almacen Norte", "Almacen Oeste", "Almacen Sur", "Almacen Este" }));
        jcbxAlmacen.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ALMACEN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jcbxAlmacen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jcbxAlmacen, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 390, 80));

        jcbxEstado.setBackground(new java.awt.Color(215, 215, 215));
        jcbxEstado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Almacen", "Partiendo", "En Camino", "Entregado" }));
        jcbxEstado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ESTADO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jcbxEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jcbxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 390, 80));

        jcbxCategoria.setBackground(new java.awt.Color(215, 215, 215));
        jcbxCategoria.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Calzado", "Casaca", "Billeteras", "Carteras", "Mochilas", "Correas", "Accesorios" }));
        jcbxCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CATEGORIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 1, 18))); // NOI18N
        jcbxCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(jcbxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 560, 390, 80));

        jbtnCambiarUsuario.setBackground(new java.awt.Color(149, 16, 43));
        jbtnCambiarUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnCambiarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCambiarUsuario.setText("CAMBIAR USUARIO");
        jbtnCambiarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCambiarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCambiarUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnCambiarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 70));

        jlabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgCambiarUsuario.jpg"))); // NOI18N
        jPanel2.add(jlabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 200, 130));

        jtblProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jtblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblProducto.setRowHeight(30);
        jtblProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProductoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtblProducto);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 320, 650, 250));

        jbtnEliminar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnEliminar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 190, 60));

        jbtnActualizar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnActualizar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 190, 60));

        jbtnRestaurar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnRestaurar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnRestaurar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnRestaurar.setText("RESTAURAR");
        jbtnRestaurar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRestaurarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnRestaurar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 190, 60));

        jbtnConsultar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnConsultar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnConsultar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConsultar.setText("CONSULTAR");
        jbtnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 500, 190, 60));

        jtblUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 16)); // NOI18N
        jtblUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblUsuario.setRowHeight(30);
        jScrollPane3.setViewportView(jtblUsuario);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 60, 650, 250));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ORIENTACIÓN DE LA INFORMACIÓN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 580, -1, 20));

        jckbUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbUsuario.setText("Usuario");
        jckbUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jckbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 600, 90, -1));

        jbgOrientacion.add(jrbInicioAFIn);
        jrbInicioAFIn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbInicioAFIn.setText("Inicio a Fin");
        jrbInicioAFIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbInicioAFIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbInicioAFInMouseClicked(evt);
            }
        });
        jPanel2.add(jrbInicioAFIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 600, 110, -1));

        jckbProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbProducto.setText("Producto");
        jckbProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jckbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 100, -1));

        jbgOrientacion.add(jrbFinAInicio);
        jrbFinAInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbFinAInicio.setText("Fin a Inicio");
        jrbFinAInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbFinAInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFinAInicioMouseClicked(evt);
            }
        });
        jPanel2.add(jrbFinAInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1370, 600, 110, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 1690, 660));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 620, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 630, 270, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, 1190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 1690, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        frmInicio inicio = new frmInicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jbtnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAgregarProductoActionPerformed
        SimpleDateFormat sdfFechas = new SimpleDateFormat("dd/MM/YYYY");
        String codigoDeProducto = jtxtCodigoDeProducto.getText();
        String estado = String.valueOf(jcbxEstado.getSelectedItem()); //En Almacen, Partiendo, En Camino, Entregado
        int cantidad = Integer.parseInt(jtxtCantidaDeProducto.getText());
        String categoria = String.valueOf(jcbxCategoria.getSelectedItem()); // Calzado, Casaca, Billeteras, Carteras, Mochilas, Correas, Accesorios
        String nombreDeProducto = jtxtNombreDeProducto.getText();
        double precioUnitario = Double.parseDouble(jtxtPrecioDelProducto.getText());
        String almacen = String.valueOf(jcbxAlmacen.getSelectedItem()); //Partida = {Almacen Centro, Almacen Norte, Almacen Oeste, Almacen Sur, Almacen Este}
        String destino = jtxtDestinoDelProducto.getText();
        String fechaDeRegistro = sdfFechas.format(jcFechaDeRegistroDeProducto.getDate());
        String fechaProgramadaDeEntrega = sdfFechas.format(jcFechaDeEntregaDeProducto.getDate());
        String codigoDeUsuario = jtxtCodigoDeUsuario.getText();
        Producto p = new Producto(codigoDeProducto, estado, cantidad, categoria, nombreDeProducto, precioUnitario, almacen, destino, fechaDeRegistro, fechaProgramadaDeEntrega, codigoDeUsuario);
        listaDeProductos.addLast(p);
        cd.sobreEscribirEnArchivoProductos(listaDeProductos);
        cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        limpiarCasillasProducto();
        jdBoleta dialogBoleta = new jdBoleta(this, true);
        dialogBoleta.setVisible(true);
    }//GEN-LAST:event_jbtnAgregarProductoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbtnCambiarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCambiarUsuarioActionPerformed
        Usuario u = new Usuario(
                jtxtCodigoDeUsuario.getText(),
                jtxtNombreDeUsuario.getText(),
                Long.parseLong(jtxtNumeroTelefonico.getText())
        );
        listaDeUsuario.add(u);

        cd.sobreEscribirEnArchivoUsuario(listaDeUsuario);
        cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        limpiarCasillasUsuario();
        limpiarCasillasProducto();
    }//GEN-LAST:event_jbtnCambiarUsuarioActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        listaDeProductos.remove(productoEncontrado);
        cd.sobreEscribirEnArchivoProductos(listaDeProductos);
        cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        limpiarCasillasUsuario();
        limpiarCasillasProducto();
        habilitarTextField();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        SimpleDateFormat sdfFechas = new SimpleDateFormat("dd/MM/YYYY");
        productoEncontrado.setCodigoDeProducto(jtxtCodigoDeProducto.getText());
        productoEncontrado.setEstado(String.valueOf(jcbxEstado.getSelectedItem()));
        productoEncontrado.setCantidad(Integer.parseInt(jtxtCantidaDeProducto.getText()));
        productoEncontrado.setCategoria(String.valueOf(jcbxCategoria.getSelectedItem()));
        productoEncontrado.setNombreDeProducto(jtxtNombreDeProducto.getText());
        productoEncontrado.setPrecioUnitario(Double.parseDouble(jtxtPrecioDelProducto.getText()));
        productoEncontrado.setAlmacen(String.valueOf(jcbxAlmacen.getSelectedItem()));
        productoEncontrado.setDestino(jtxtDestinoDelProducto.getText());
        productoEncontrado.setFechaDeRegistro(sdfFechas.format(jcFechaDeRegistroDeProducto.getDate()));
        productoEncontrado.setFechaProgramadaDeEntrega(sdfFechas.format(jcFechaDeEntregaDeProducto.getDate()));
        cd.sobreEscribirEnArchivoProductos(listaDeProductos);
        cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        habilitarTextField();
        deshabilitarBoton();
        limpiarCasillasProducto();
        limpiarCasillasUsuario();
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jbtnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRestaurarActionPerformed
        limpiarCasillasProducto();
        limpiarCasillasUsuario();
        habilitarTextField();
        deshabilitarBoton();
    }//GEN-LAST:event_jbtnRestaurarActionPerformed

    private void jbtnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsultarActionPerformed
        String codigoProducto = jtxtCodigoDeProducto.getText();
        if (codigoProducto.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Ingrese un codigo por favor");
        } else {
            try {
                productoEncontrado = buscarProducto(codigoProducto);/*REDUNDANCIA PUEDE SER VOID*/
                usuarioEncontrado = buscarUsuario(productoEncontrado.getCodigoDeUsuario());
            } catch (NullPointerException nullPointerException) {
                nullPointerException.getMessage();
                nullPointerException.getLocalizedMessage();
            }
            if (productoEncontrado != null) {
                jcbxCategoria.setSelectedItem(productoEncontrado.getCategoria());
                jtxtNombreDeProducto.setText(productoEncontrado.getNombreDeProducto());
                jtxtPrecioDelProducto.setText(String.valueOf(productoEncontrado.getPrecioUnitario()));
                jcbxAlmacen.setSelectedItem(productoEncontrado.getAlmacen());
                jtxtDestinoDelProducto.setText(productoEncontrado.getDestino());
                jtxtCantidaDeProducto.setText(String.valueOf(productoEncontrado.getCantidad()));
                jcbxEstado.setSelectedItem(productoEncontrado.getEstado());
                SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
                try {
                    jcFechaDeEntregaDeProducto.setDate(df.parse(productoEncontrado.getFechaProgramadaDeEntrega()));
                    jcFechaDeRegistroDeProducto.setDate(df.parse(productoEncontrado.getFechaDeRegistro()));
                } catch (Exception e) {
                    e.getMessage();
                    e.getLocalizedMessage();
                }
                jtxtNumeroTelefonico.setText(String.valueOf(usuarioEncontrado.getTelefono()));
                jtxtCodigoDeUsuario.setText(usuarioEncontrado.getCodigo());
                jtxtNombreDeUsuario.setText(usuarioEncontrado.getNombre());
                desabilitarTextField();
                habilitarBoton();
            } else {
                JOptionPane.showMessageDialog(this, "El codigo: " + codigoProducto + ", no esta en la lista...", "NO SE ENCUENTRA EN LA LISTA", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnConsultarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        jckbProducto.setSelected(true);
        jckbUsuario.setSelected(true);
        jrbInicioAFIn.setSelected(true);
        deshabilitarBoton();
    }//GEN-LAST:event_formWindowOpened

    private void jrbInicioAFInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbInicioAFInMouseClicked
        if (!jckbProducto.isSelected() && !jckbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        }
        if (jckbProducto.isSelected() && jckbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        }
        if (jckbProducto.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        }
        if (jckbUsuario.isSelected()) {
            cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        }
    }//GEN-LAST:event_jrbInicioAFInMouseClicked

    private void jrbFinAInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFinAInicioMouseClicked
        if (!jckbProducto.isSelected() && !jckbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosFinInicio(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosFinInicio(dtmTablaDeUsuarios);
        }
        if (jckbProducto.isSelected() && jckbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosFinInicio(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosFinInicio(dtmTablaDeUsuarios);
        }
        if (jckbProducto.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosFinInicio(dtmTablaDeProductos);
        }
        if (jckbUsuario.isSelected()) {
            cd.sobreEscribirTablaDeUsuariosFinInicio(dtmTablaDeUsuarios);
        }
    }//GEN-LAST:event_jrbFinAInicioMouseClicked

    private void jtxtCodigoDeUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoDeUsuarioMouseExited
        Iterator<Usuario> itUsuario = listaDeUsuario.iterator();
        String codigoUsuario = jtxtCodigoDeUsuario.getText();
        String nombreUsuario = jtxtNombreDeUsuario.getText();
        long telefono;
        if (jtxtNumeroTelefonico.getText().equalsIgnoreCase("")) {
            telefono = 0;
        } else {
            telefono = Long.parseLong(jtxtNumeroTelefonico.getText());
        }
        int valor;
        while (itUsuario.hasNext()) {
            Usuario u = itUsuario.next();
            if (u.getCodigo().equalsIgnoreCase(codigoUsuario) && u.getNombre().equalsIgnoreCase(nombreUsuario) && u.getTelefono() == telefono) {
            } else {
                if (codigoUsuario.equalsIgnoreCase(u.getCodigo())) {
                    valor = JOptionPane.showConfirmDialog(this, "ESE CODIGO ESTA REGISTRADO EN LA BASE DE DATOS\n¿DESEA USAR EL CLIENTE YA REGISTRADO?", "USUARIO REGISTRADO", JOptionPane.INFORMATION_MESSAGE);
                    if (valor == 0) {
                        jtxtNombreDeUsuario.setText(u.getNombre());
                        jtxtNumeroTelefonico.setText(String.valueOf(u.getTelefono()));
                    }
                    if (valor == 1 || valor == 2) {
                        jtxtNombreDeUsuario.setText("");
                        jtxtNumeroTelefonico.setText("");
                        jtxtCodigoDeUsuario.setText("");
                    }
                }
            }
        }
    }//GEN-LAST:event_jtxtCodigoDeUsuarioMouseExited

    private void jtblProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProductoMouseClicked
//        int numeroDeFila = jtblProducto.getSelectedRow();
//        if (numeroDeFila != -1) {
////            Object[] filaProducto = {p.getCodigoDeProducto(), p.getEstado(), p.getCantidad(), p.getCategoria(),
////                p.getNombreDeProducto(), dfProducto.format(p.getPrecioUnitario()), p.getAlmacen(), p.getDestino(), p.getFechaDeRegistro(),
////                p.getFechaProgramadaDeEntrega(), p.getCodigoDeUsuario(), dfProducto.format(p.calcularPrecioDeUnTipoDeProducto())
////            };
//            String codigoDeProducto = jtblProducto.getValueAt(numeroDeFila, 0).toString();
//            String estado = jtblProducto.getValueAt(numeroDeFila, 1).toString(); //En Almacen, Partiendo, En Camino, Entregado
//            int cantidad = Integer.parseInt(jtblProducto.getValueAt(numeroDeFila, 2).toString());
//            String categoria = jtblProducto.getValueAt(numeroDeFila, 3).toString(); // Calzado, Casaca, Billeteras, Carteras, Mochilas, Correas, Accesorios
//            String nombreDeProducto = jtblProducto.getValueAt(numeroDeFila, 4).toString();
//            double precioUnitario = Double.parseDouble(jtblProducto.getValueAt(numeroDeFila, 5).toString());
//            String almacen = jtblProducto.getValueAt(numeroDeFila, 6).toString(); //Partida = {Almacen Centro, Almacen Norte, Almacen Oeste, Almacen Sur, Almacen Este}
//            String destino = jtblProducto.getValueAt(numeroDeFila, 7).toString();
//            String fechaDeRegistro = jtblProducto.getValueAt(numeroDeFila, 8).toString();
//            String fechaProgramadaDeEntrega = jtblProducto.getValueAt(numeroDeFila, 9).toString();
//            String codigoDeUsuario = jtblProducto.getValueAt(numeroDeFila, 10).toString();
//            
//            Producto p = new Producto(codigoDeProducto, estado, cantidad, categoria, nombreDeProducto, precioUnitario, almacen, destino, fechaDeRegistro, fechaProgramadaDeEntrega, codigoDeUsuario);
//            System.out.println(p.toString());;
//        }
    }//GEN-LAST:event_jtblProductoMouseClicked

    private Producto buscarProducto(String codigo) {
        Iterator<Producto> itProducto = listaDeProductos.iterator();
        while (itProducto.hasNext()) {
            Producto p = itProducto.next();
            if (p.getCodigoDeProducto().equalsIgnoreCase(codigo)) {
                productoEncontrado = p;
                break;
            } else {
                productoEncontrado = null;
            }
        }
        return productoEncontrado;
    }

    private Usuario buscarUsuario(String codigo) {
        Iterator<Usuario> itUsario = listaDeUsuario.iterator();
        while (itUsario.hasNext()) {
            Usuario u = itUsario.next();
            if (u.getCodigo().equalsIgnoreCase(codigo)) {
                usuarioEncontrado = u;
                break;
            } else {
                usuarioEncontrado = new Usuario("USUARIO ELIMINADO", "CODIGO ELIMINADO", 0);
            }
        }
        return usuarioEncontrado;
    }

    private void habilitarTextField() {
        jtxtCodigoDeUsuario.setEnabled(true);
        jtxtNombreDeUsuario.setEnabled(true);
        jtxtNumeroTelefonico.setEnabled(true);
    }

    private void desabilitarTextField() {
        jtxtCodigoDeUsuario.setEnabled(false);
        jtxtNombreDeUsuario.setEnabled(false);
        jtxtNumeroTelefonico.setEnabled(false);
    }

    private void habilitarBoton() {
        jbtnEliminar.setEnabled(true);
        jbtnActualizar.setEnabled(true);
        jbtnAgregarProducto.setEnabled(false);
    }

    private void deshabilitarBoton() {
        jbtnEliminar.setEnabled(false);
        jbtnActualizar.setEnabled(false);
        jbtnAgregarProducto.setEnabled(true);
    }

    private void limpiarCasillasProducto() {
        jcFechaDeEntregaDeProducto.requestFocus();
        jcFechaDeEntregaDeProducto.setDate(null);
        jcFechaDeRegistroDeProducto.setDate(null);
        jtxtCantidaDeProducto.setText("");
        jtxtCodigoDeProducto.setText("");
        jtxtDestinoDelProducto.setText("");
        jtxtNombreDeProducto.setText("");
        jtxtPrecioDelProducto.setText("");
    }

    private void limpiarCasillasUsuario() {
        jtxtNombreDeUsuario.setText("");
        jtxtNumeroTelefonico.setText("");
        jtxtCodigoDeUsuario.setText("");
        jtxtNombreDeUsuario.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProductoYusuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProductoYusuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProductoYusuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAgregarProductoYusuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAgregarProductoYusuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.ButtonGroup jbgOrientacion;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnAgregarProducto;
    private javax.swing.JButton jbtnCambiarUsuario;
    private javax.swing.JButton jbtnConsultar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnRestaurar;
    private com.toedter.calendar.JDateChooser jcFechaDeEntregaDeProducto;
    private com.toedter.calendar.JDateChooser jcFechaDeRegistroDeProducto;
    private javax.swing.JComboBox<String> jcbxAlmacen;
    private javax.swing.JComboBox<String> jcbxCategoria;
    private javax.swing.JComboBox<String> jcbxEstado;
    private javax.swing.JCheckBox jckbProducto;
    private javax.swing.JCheckBox jckbUsuario;
    private javax.swing.JLabel jlabelProducto;
    private javax.swing.JLabel jlabelUsuario;
    private javax.swing.JRadioButton jrbFinAInicio;
    private javax.swing.JRadioButton jrbInicioAFIn;
    private javax.swing.JTable jtblProducto;
    private javax.swing.JTable jtblUsuario;
    private javax.swing.JTextField jtxtCantidaDeProducto;
    private javax.swing.JTextField jtxtCodigoDeProducto;
    private javax.swing.JTextField jtxtCodigoDeUsuario;
    private javax.swing.JTextField jtxtDestinoDelProducto;
    private javax.swing.JTextField jtxtNombreDeProducto;
    private javax.swing.JTextField jtxtNombreDeUsuario;
    private javax.swing.JTextField jtxtNumeroTelefonico;
    private javax.swing.JTextField jtxtPrecioDelProducto;
    // End of variables declaration//GEN-END:variables
}
