/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import Controladores.Plantilla;

/**
 *
 * @author yanni
 */
public class frmExportarPDF extends javax.swing.JFrame {

    Plantilla p = new Plantilla();

    public frmExportarPDF() {
        initComponents();
        /*DISEÑO*/
        escalarImagenes();
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }
    
    private void escalarImagenes(){
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelPDF, "src/Imagenes/imgPDFjpg.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoDocumneto = new javax.swing.ButtonGroup();
        grupoGerente = new javax.swing.ButtonGroup();
        grupoNombre = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jlabelPDF = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelOpcionesGenerales = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtxtNombreDelDocumento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jckbExportarEmpleados = new javax.swing.JCheckBox();
        jrbPorDefectoNombreDocumento = new javax.swing.JRadioButton();
        jrbPersonalizadoNombreDocumento = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jtxtNombreDelGerente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrbPorDefectoNombreGerente = new javax.swing.JRadioButton();
        jrbPersonalizadoNombreGerente = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jrbPersonalizadoTipoDeDocumento = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jckbExportarProducto = new javax.swing.JCheckBox();
        jckbExportarAlmacenes = new javax.swing.JCheckBox();
        jckbExportarUsuarios = new javax.swing.JCheckBox();
        jrbPorDefectoTipoDeDocumento = new javax.swing.JRadioButton();
        jrbTodos = new javax.swing.JRadioButton();
        jcbxTipoDeDocumento = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        panelOpcionesEspecificas = new javax.swing.JPanel();
        panelOpcionesEspecificas1 = new javax.swing.JPanel();
        jbtnInicio1 = new javax.swing.JButton();
        jbtnInicio2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXPORTAR PDF");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 40));

        jlabelPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgPDFjpg.jpg"))); // NOI18N
        jPanel2.add(jlabelPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 300, 390));

        jTabbedPane1.setBackground(new java.awt.Color(149, 16, 43));
        jTabbedPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jTabbedPane1.setToolTipText("");
        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jTabbedPane1.setOpaque(true);

        panelOpcionesGenerales.setBackground(new java.awt.Color(255, 255, 255));
        panelOpcionesGenerales.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(215, 215, 215));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NOMBRE DE DOCUMENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreDelDocumento.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNombreDelDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNombreDelDocumento.setBorder(null);
        jPanel4.add(jtxtNombreDelDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        panelOpcionesGenerales.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 390, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("NOMBRE DEL DOCUMENTO");
        panelOpcionesGenerales.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 40));

        jckbExportarEmpleados.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbExportarEmpleados.setText("Tabla De Empleados");
        jckbExportarEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jckbExportarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbExportarEmpleadosActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jckbExportarEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 187, -1));

        grupoNombre.add(jrbPorDefectoNombreDocumento);
        jrbPorDefectoNombreDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPorDefectoNombreDocumento.setText("Por defecto");
        jrbPorDefectoNombreDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPorDefectoNombreDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPorDefectoNombreDocumentoMouseClicked(evt);
            }
        });
        jrbPorDefectoNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorDefectoNombreDocumentoActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPorDefectoNombreDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, -1));

        grupoNombre.add(jrbPersonalizadoNombreDocumento);
        jrbPersonalizadoNombreDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPersonalizadoNombreDocumento.setText("Personalizado");
        jrbPersonalizadoNombreDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPersonalizadoNombreDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPersonalizadoNombreDocumentoMouseClicked(evt);
            }
        });
        jrbPersonalizadoNombreDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPersonalizadoNombreDocumentoActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPersonalizadoNombreDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 180, -1));

        jPanel6.setBackground(new java.awt.Color(215, 215, 215));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NOMBRE DEL GERENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreDelGerente.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNombreDelGerente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNombreDelGerente.setBorder(null);
        jPanel6.add(jtxtNombreDelGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 370, 40));

        panelOpcionesGenerales.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 390, 70));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("EXPORTAR");
        panelOpcionesGenerales.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 40));

        grupoGerente.add(jrbPorDefectoNombreGerente);
        jrbPorDefectoNombreGerente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPorDefectoNombreGerente.setText("Por defecto");
        jrbPorDefectoNombreGerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPorDefectoNombreGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPorDefectoNombreGerenteMouseClicked(evt);
            }
        });
        jrbPorDefectoNombreGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorDefectoNombreGerenteActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPorDefectoNombreGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 180, -1));

        grupoGerente.add(jrbPersonalizadoNombreGerente);
        jrbPersonalizadoNombreGerente.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPersonalizadoNombreGerente.setText("Personalizado");
        jrbPersonalizadoNombreGerente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPersonalizadoNombreGerente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPersonalizadoNombreGerenteMouseClicked(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPersonalizadoNombreGerente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("NOMBRE DEL GERENTE");
        panelOpcionesGenerales.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 360, 40));

        grupoDocumneto.add(jrbPersonalizadoTipoDeDocumento);
        jrbPersonalizadoTipoDeDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPersonalizadoTipoDeDocumento.setText("Personalizado");
        jrbPersonalizadoTipoDeDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPersonalizadoTipoDeDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPersonalizadoTipoDeDocumentoMouseClicked(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPersonalizadoTipoDeDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 180, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TIPO DE DOCUMENTO");
        panelOpcionesGenerales.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 360, 40));

        jckbExportarProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbExportarProducto.setText("Tabla De Productos");
        jckbExportarProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOpcionesGenerales.add(jckbExportarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 187, -1));

        jckbExportarAlmacenes.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbExportarAlmacenes.setText("Tabla De Almacenes");
        jckbExportarAlmacenes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelOpcionesGenerales.add(jckbExportarAlmacenes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 187, -1));

        jckbExportarUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jckbExportarUsuarios.setText("Tabla De Usuarios");
        jckbExportarUsuarios.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jckbExportarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jckbExportarUsuariosActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jckbExportarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 187, -1));

        grupoDocumneto.add(jrbPorDefectoTipoDeDocumento);
        jrbPorDefectoTipoDeDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPorDefectoTipoDeDocumento.setText("Por defecto");
        jrbPorDefectoTipoDeDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPorDefectoTipoDeDocumento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPorDefectoTipoDeDocumentoMouseClicked(evt);
            }
        });
        jrbPorDefectoTipoDeDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbPorDefectoTipoDeDocumentoActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jrbPorDefectoTipoDeDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jrbTodos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbTodos.setText("Todos");
        jrbTodos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbTodos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbTodosMouseClicked(evt);
            }
        });
        jrbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosActionPerformed(evt);
            }
        });
        panelOpcionesGenerales.add(jrbTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 380, -1));

        jcbxTipoDeDocumento.setBackground(new java.awt.Color(215, 215, 215));
        jcbxTipoDeDocumento.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbxTipoDeDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PDF", "WORD" }));
        jcbxTipoDeDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TIPO DE DOCUMENTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jcbxTipoDeDocumento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelOpcionesGenerales.add(jcbxTipoDeDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 390, 70));

        jSeparator2.setBackground(new java.awt.Color(149, 16, 43));
        jSeparator2.setForeground(new java.awt.Color(149, 16, 43));
        panelOpcionesGenerales.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 750, 10));

        jTabbedPane1.addTab("OPCIONES GENERALES", panelOpcionesGenerales);

        panelOpcionesEspecificas.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelOpcionesEspecificasLayout = new javax.swing.GroupLayout(panelOpcionesEspecificas);
        panelOpcionesEspecificas.setLayout(panelOpcionesEspecificasLayout);
        panelOpcionesEspecificasLayout.setHorizontalGroup(
            panelOpcionesEspecificasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        panelOpcionesEspecificasLayout.setVerticalGroup(
            panelOpcionesEspecificasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("OPCIONES ESPECÍFICAS", panelOpcionesEspecificas);

        panelOpcionesEspecificas1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelOpcionesEspecificas1Layout = new javax.swing.GroupLayout(panelOpcionesEspecificas1);
        panelOpcionesEspecificas1.setLayout(panelOpcionesEspecificas1Layout);
        panelOpcionesEspecificas1Layout.setHorizontalGroup(
            panelOpcionesEspecificas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        panelOpcionesEspecificas1Layout.setVerticalGroup(
            panelOpcionesEspecificas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ELIMINAR, ABRIR Y ACTUALIZAR DOCUMENTO", panelOpcionesEspecificas1);

        jPanel2.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 790, 390));

        jbtnInicio1.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio1.setText("EXPORTAR");
        jbtnInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicio1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 180, 60));

        jbtnInicio2.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio2.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio2.setText("INICIO");
        jbtnInicio2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicio2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 450, 180, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 1150, 520));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 490, 270, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 770, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 1140, 530));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jrbPorDefectoNombreDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPorDefectoNombreDocumentoMouseClicked
        if (jrbPorDefectoNombreDocumento.isSelected()) {
            jtxtNombreDelDocumento.setText("TABLAS RENZO COSTA S.A.C");
        }
    }//GEN-LAST:event_jrbPorDefectoNombreDocumentoMouseClicked

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jrbPersonalizadoNombreDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPersonalizadoNombreDocumentoMouseClicked
        if (jrbPersonalizadoNombreDocumento.isSelected()) {
            jtxtNombreDelDocumento.setText("");
        }
    }//GEN-LAST:event_jrbPersonalizadoNombreDocumentoMouseClicked

    private void jrbPorDefectoNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorDefectoNombreDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorDefectoNombreDocumentoActionPerformed

    private void jrbPorDefectoNombreGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPorDefectoNombreGerenteMouseClicked
        if (jrbPorDefectoNombreGerente.isSelected()) {
            jtxtNombreDelGerente.setText("RENZO COSTA S.A.C");
        }
    }//GEN-LAST:event_jrbPorDefectoNombreGerenteMouseClicked

    private void jrbPorDefectoNombreGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorDefectoNombreGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorDefectoNombreGerenteActionPerformed

    private void jrbPersonalizadoNombreGerenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPersonalizadoNombreGerenteMouseClicked
        if (jrbPersonalizadoNombreGerente.isSelected()) {
            jtxtNombreDelGerente.setText("");
        }
    }//GEN-LAST:event_jrbPersonalizadoNombreGerenteMouseClicked

    private void jrbPersonalizadoTipoDeDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPersonalizadoTipoDeDocumentoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPersonalizadoTipoDeDocumentoMouseClicked

    private void jckbExportarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbExportarEmpleadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jckbExportarEmpleadosActionPerformed

    private void jckbExportarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jckbExportarUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jckbExportarUsuariosActionPerformed

    private void jrbPorDefectoTipoDeDocumentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPorDefectoTipoDeDocumentoMouseClicked
        if (jrbPorDefectoTipoDeDocumento.isSelected()) {
            jcbxTipoDeDocumento.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jrbPorDefectoTipoDeDocumentoMouseClicked

    private void jrbPorDefectoTipoDeDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPorDefectoTipoDeDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPorDefectoTipoDeDocumentoActionPerformed

    private void jrbTodosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbTodosMouseClicked
        if (jrbTodos.isSelected()) {
            jckbExportarAlmacenes.setSelected(true);
            jckbExportarEmpleados.setSelected(true);
            jckbExportarProducto.setSelected(true);
            jckbExportarUsuarios.setSelected(true);
        } else {
            jckbExportarAlmacenes.setSelected(false);
            jckbExportarEmpleados.setSelected(false);
            jckbExportarProducto.setSelected(false);
            jckbExportarUsuarios.setSelected(false);
        }
    }//GEN-LAST:event_jrbTodosMouseClicked

    private void jrbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTodosActionPerformed

    private void jbtnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicio1ActionPerformed
        String nombreDocumento = jtxtNombreDelDocumento.getText();
        String nombreGerente = jtxtNombreDelGerente.getText();
        String formato = jcbxTipoDeDocumento.getSelectedItem().toString().toLowerCase();
        boolean imprimirTabla[] = {jckbExportarUsuarios.isSelected(),
            jckbExportarEmpleados.isSelected(), jckbExportarAlmacenes.isSelected(),
            jckbExportarProducto.isSelected()};
        Plantilla p = new Plantilla(nombreGerente, nombreDocumento, formato, imprimirTabla);
        p.buildPlantilla();
        limpiarFrame();
    }//GEN-LAST:event_jbtnInicio1ActionPerformed

    private void jbtnInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicio2ActionPerformed
        frmInicio i = new frmInicio();
        i.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnInicio2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        establecerValoresAlFrame();
    }//GEN-LAST:event_formWindowOpened

    private void jrbPersonalizadoNombreDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbPersonalizadoNombreDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbPersonalizadoNombreDocumentoActionPerformed

    private void establecerValoresAlFrame() {
        jckbExportarAlmacenes.setSelected(true);
        jckbExportarEmpleados.setSelected(true);
        jckbExportarProducto.setSelected(true);
        jckbExportarUsuarios.setSelected(true);
        jrbPorDefectoNombreDocumento.setSelected(true);
        jrbPorDefectoNombreGerente.setSelected(true);
        jrbPorDefectoTipoDeDocumento.setSelected(true);
        jrbTodos.setSelected(true);
        jtxtNombreDelDocumento.setText("TABLAS RENZO COSTA S.A.C.");
        jtxtNombreDelGerente.setText("RENZO COSTA S.A.C.");
    }

    private void limpiarFrame() {
        jtxtNombreDelDocumento.setText("");
        jtxtNombreDelGerente.setText("");
        jrbPorDefectoNombreDocumento.setSelected(false);
        jrbPorDefectoNombreGerente.setSelected(false);
        jrbPorDefectoTipoDeDocumento.setSelected(false);
        jrbPersonalizadoNombreDocumento.setSelected(true);
        jrbPersonalizadoNombreGerente.setSelected(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmExportarPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmExportarPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmExportarPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmExportarPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmExportarPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoDocumneto;
    private javax.swing.ButtonGroup grupoGerente;
    private javax.swing.ButtonGroup grupoNombre;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbtnInicio1;
    private javax.swing.JButton jbtnInicio2;
    private javax.swing.JComboBox<String> jcbxTipoDeDocumento;
    private javax.swing.JCheckBox jckbExportarAlmacenes;
    private javax.swing.JCheckBox jckbExportarEmpleados;
    private javax.swing.JCheckBox jckbExportarProducto;
    private javax.swing.JCheckBox jckbExportarUsuarios;
    private javax.swing.JLabel jlabelPDF;
    private javax.swing.JRadioButton jrbPersonalizadoNombreDocumento;
    private javax.swing.JRadioButton jrbPersonalizadoNombreGerente;
    private javax.swing.JRadioButton jrbPersonalizadoTipoDeDocumento;
    private javax.swing.JRadioButton jrbPorDefectoNombreDocumento;
    private javax.swing.JRadioButton jrbPorDefectoNombreGerente;
    private javax.swing.JRadioButton jrbPorDefectoTipoDeDocumento;
    private javax.swing.JRadioButton jrbTodos;
    private javax.swing.JTextField jtxtNombreDelDocumento;
    private javax.swing.JTextField jtxtNombreDelGerente;
    private javax.swing.JPanel panelOpcionesEspecificas;
    private javax.swing.JPanel panelOpcionesEspecificas1;
    private javax.swing.JPanel panelOpcionesGenerales;
    // End of variables declaration//GEN-END:variables
}
