/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Producto;
import Controladores.ControladorData;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Iterator;
import java.util.LinkedList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author yanni
 */
public class frmEstadisticaEmpresariales extends javax.swing.JFrame {
    LinkedList<Producto> listaProducto;
    ControladorData cd;
    /**
     * Creates new form frmEstadisticaEmpresariales
     */
    public frmEstadisticaEmpresariales() {
        initComponents();
        /*OP OPERACIONAL*/
        cd = new ControladorData();
        listaProducto = cd.instanciarListaProducto();
        /*OP DISEÑO*/
        setBackground(new Color(0,0,0,0));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtnInicio = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jpanelGraficoLinealAnual = new javax.swing.JPanel();
        Consultar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnInicio.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 230, 60));

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ESTADÍSTICAS EMPRESARIALES");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        jpanelGraficoLinealAnual.setBackground(new java.awt.Color(215, 215, 215));
        jpanelGraficoLinealAnual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpanelGraficoLinealAnualLayout = new javax.swing.GroupLayout(jpanelGraficoLinealAnual);
        jpanelGraficoLinealAnual.setLayout(jpanelGraficoLinealAnualLayout);
        jpanelGraficoLinealAnualLayout.setHorizontalGroup(
            jpanelGraficoLinealAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jpanelGraficoLinealAnualLayout.setVerticalGroup(
            jpanelGraficoLinealAnualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 418, Short.MAX_VALUE)
        );

        jPanel2.add(jpanelGraficoLinealAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 820, 420));

        Consultar.setBackground(new java.awt.Color(149, 16, 43));
        Consultar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("CONSULTAR");
        Consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 210, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 880, 590));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 540, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 880, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        frmInicio inicio = new frmInicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
        graficarFuncionLineal();
    }//GEN-LAST:event_ConsultarActionPerformed

    private void graficarFuncionLineal(){
        jpanelGraficoLinealAnual.removeAll();
        int[] cantidadSolicitadaPorMeses = obtenerCantidadSolitidadPorAñoEnMeses();
        int[] cantidadEntregadaPorMeses = obtenerCantidadEntregadaPorAñoEnMeses();
        int contadorDeMes = 1;
        XYSeries seriesSolicitadas = new XYSeries("CANTIDAD DE PRODUCTO SOLICITADOS");
        XYSeries seriesEntregadas = new XYSeries("CANTIDAD DE PRODUCTO ENTREGADOS");
        
        for (int i = 0; i < 12; i++) {
            seriesSolicitadas.add(contadorDeMes,cantidadSolicitadaPorMeses[i]);
            contadorDeMes++;
        }
        contadorDeMes = 1;
        for (int i = 0; i < 12; i++) {
            seriesEntregadas.add(contadorDeMes,cantidadEntregadaPorMeses[i]);
            contadorDeMes++;
        }
 
        XYSeriesCollection dataSet = new XYSeriesCollection();
        dataSet.addSeries(seriesSolicitadas);
        dataSet.addSeries(seriesEntregadas);
        
        JFreeChart oChart = ChartFactory.createXYLineChart(
                "CANTIDAD SOLICITADA POR MES",
                "MES",
                "CANTIDAD",
                dataSet,
                PlotOrientation.VERTICAL,
                true,
                true,
                false
        );
        
        ChartPanel oPanel = new ChartPanel(oChart);
        oPanel.setSize(new Dimension(jpanelGraficoLinealAnual.getWidth(), jpanelGraficoLinealAnual.getHeight()));
        oPanel.setMouseWheelEnabled(true);
        jpanelGraficoLinealAnual.setLayout(new BorderLayout());
        jpanelGraficoLinealAnual.add(oPanel, BorderLayout.NORTH);
        
        pack();
        repaint();
    }
    
    private int[] obtenerCantidadSolitidadPorAñoEnMeses(){
        int[] meses = new int[12];
        Iterator<Producto> itProducto = listaProducto.iterator();
        Producto p = new Producto();
        
        while(itProducto.hasNext()){
            p = itProducto.next();
            meses[0] += obtene("01", p);
            meses[1] += obtene("02", p);
            meses[2] += obtene("03", p);
            meses[3] += obtene("04", p);
            meses[4] += obtene("05", p);
            meses[5] += obtene("06", p);
            meses[6] += obtene("07", p);
            meses[7] += obtene("08", p);
            meses[8] += obtene("09", p);
            meses[9] += obtene("10", p);
            meses[10] += obtene("11", p);
            meses[11] += obtene("12", p);
        }
        
        return meses;
    }
    
    private int obtene(String mes, Producto p){
        String[] valores = p.getFechaDeRegistro().split("/");
        if (valores[1].equalsIgnoreCase(mes)) {
            return 1;
        }
        return 0;
    }
    
    private int[] obtenerCantidadEntregadaPorAñoEnMeses(){
        int[] meses = new int[12];
        Iterator<Producto> itProducto = listaProducto.iterator();
        Producto p = new Producto();
        
        while(itProducto.hasNext()){
            p = itProducto.next();
            meses[0] += obtenerMesEntregadoDelProducto("01", p);
            meses[1] += obtenerMesEntregadoDelProducto("02", p);
            meses[2] += obtenerMesEntregadoDelProducto("03", p);
            meses[3] += obtenerMesEntregadoDelProducto("04", p);
            meses[4] += obtenerMesEntregadoDelProducto("05", p);
            meses[5] += obtenerMesEntregadoDelProducto("06", p);
            meses[6] += obtenerMesEntregadoDelProducto("07", p);
            meses[7] += obtenerMesEntregadoDelProducto("08", p);
            meses[8] += obtenerMesEntregadoDelProducto("09", p);
            meses[9] += obtenerMesEntregadoDelProducto("10", p);
            meses[10] += obtenerMesEntregadoDelProducto("11", p);
            meses[11] += obtenerMesEntregadoDelProducto("12", p);
        }
        
        return meses;
    }
    
    private int obtenerMesEntregadoDelProducto(String mes, Producto p){
        String[] valores = p.getFechaProgramadaDeEntrega().split("/");
        if (valores[1].equalsIgnoreCase(mes)) {
            return 1;
        }
        return 0;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticaEmpresariales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticaEmpresariales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticaEmpresariales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEstadisticaEmpresariales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEstadisticaEmpresariales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JPanel jpanelGraficoLinealAnual;
    // End of variables declaration//GEN-END:variables
}
