package Frames;

import Clases.Empleado;
import Clases.Producto;
import Clases.Usuario;
import ConexionDB.Conexion;
import Controladores.ControladorData;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.LinkedList;

/**
 *
 * @author yanni
 */
public class frmInicio extends javax.swing.JFrame {

    LinkedList<Usuario> listaUsuario;
    LinkedList<Producto> listaProducto;
    LinkedList<Empleado> listaEmpleado;
    ControladorData cd;

    public frmInicio() {
        initComponents();
        /*OP OPERACIONAL*/
        cd = new ControladorData();
        listaEmpleado = cd.instanciarListaEmpleado();
        listaProducto = cd.instanciarListaProducto();
        listaUsuario = cd.instanciarLinkedListUsuario();
        /*OP DISEÑO*/
        frmInicio.this.setLocationRelativeTo(null);
        frmInicio.this.setBackground(new Color(0, 0, 0, 0));
        escalarImagenes();
    }

    private void escalarImagenes() {
        rsscalelabel.RSScaleLabel.setScaleLabel(jbLogoDeEntrada, "src/Imagenes/imgRenzoCostaTiendaGeneral.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbAgregarProductoYusuarios, "src/Imagenes/agregarCliente.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbEstadistica, "src/Imagenes/estadisticas.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbListarProducto, "src/Imagenes/listarProducto.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbListarUsuario, "src/Imagenes/busquedaDeUsuario.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbExportarPDF, "src/Imagenes/imgPdf.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jbDatosEmpresarial, "src/Imagenes/imgDatosEmpresariales.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelDB, "src/Imagenes/imgDB.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(jlabelArbol, "src/Imagenes/imgArbol.jpg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbLogoDeEntrada = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbListarProducto = new javax.swing.JLabel();
        jbAgregarProductoYusuarios = new javax.swing.JLabel();
        jbEstadistica = new javax.swing.JLabel();
        jbExportarPDF = new javax.swing.JLabel();
        jbListarUsuario = new javax.swing.JLabel();
        jbDatosEmpresarial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jlabelDB = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jbtnDesconectar = new javax.swing.JButton();
        jbtnConectar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jbtnActualizar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jlabelArbol = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbRegistrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbLogoDeEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgRenzoCostaTiendaGeneral.jpg"))); // NOI18N
        jPanel2.add(jbLogoDeEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 670));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BIENVENIDO AL SISTEMA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 490, 40));

        jbListarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listarProducto.jpg"))); // NOI18N
        jbListarProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbListarProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbListarProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbListarProductoMouseClicked(evt);
            }
        });
        jPanel2.add(jbListarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 90, 140, 130));

        jbAgregarProductoYusuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbAgregarProductoYusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbAgregarProductoYusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarCliente.jpg"))); // NOI18N
        jbAgregarProductoYusuarios.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbAgregarProductoYusuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbAgregarProductoYusuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAgregarProductoYusuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAgregarProductoYusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbAgregarProductoYusuariosMouseClicked(evt);
            }
        });
        jPanel2.add(jbAgregarProductoYusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 140, 130));

        jbEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/estadisticas.jpg"))); // NOI18N
        jbEstadistica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbEstadistica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbEstadistica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbEstadisticaMouseClicked(evt);
            }
        });
        jPanel2.add(jbEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 140, 130));

        jbExportarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarCliente.jpg"))); // NOI18N
        jbExportarPDF.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbExportarPDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExportarPDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbExportarPDFMouseClicked(evt);
            }
        });
        jPanel2.add(jbExportarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 290, 140, 130));

        jbListarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/busquedaDeUsuario.jpg"))); // NOI18N
        jbListarUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbListarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbListarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbListarUsuarioMouseClicked(evt);
            }
        });
        jPanel2.add(jbListarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 140, 130));

        jbDatosEmpresarial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarCliente.jpg"))); // NOI18N
        jbDatosEmpresarial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jbDatosEmpresarial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbDatosEmpresarial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbDatosEmpresarialMouseClicked(evt);
            }
        });
        jPanel2.add(jbDatosEmpresarial, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 140, 130));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DE SEGUIMIENTO DE PRODUCTOS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 490, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ORDENADO");
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, 130, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("GENERAR VENTA");
        jLabel12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 140, 30));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("ALMACEN");
        jLabel13.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 140, 30));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("LISTAR PRODUCTO");
        jLabel14.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 220, 140, 30));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ESTADISTICAS DE");
        jLabel15.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 220, 140, 30));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("BASE DE DATOS");
        jLabel16.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 290, 30));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("EMPRESARIALES");
        jLabel17.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 140, 30));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("DATOS");
        jLabel18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 140, 30));

        jlabelDB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgDB.jpg"))); // NOI18N
        jlabelDB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jlabelDB.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelDBMouseClicked(evt);
            }
        });
        jPanel2.add(jlabelDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 490, 140, 130));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("BUSCAR CLIENTE");
        jLabel19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 140, 30));

        jbtnDesconectar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnDesconectar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnDesconectar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnDesconectar.setText("DESCONECTAR");
        jbtnDesconectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDesconectarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDesconectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, 140, -1));

        jbtnConectar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnConectar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnConectar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnConectar.setText("CONECTAR ");
        jbtnConectar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConectarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnConectar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 490, 140, 40));

        jSeparator2.setForeground(new java.awt.Color(149, 16, 43));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 440, 10));

        jbtnActualizar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnActualizar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnActualizar.setText("ACTUALIZAR");
        jbtnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 140, 30));

        jbtnEliminar.setBackground(new java.awt.Color(149, 16, 43));
        jbtnEliminar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 140, 30));

        jlabelArbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jlabelArbol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jlabelArbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabelArbolMouseClicked(evt);
            }
        });
        jPanel2.add(jlabelArbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 490, 130, 130));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("EXPORTAR PDF");
        jLabel20.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 140, 30));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("LISTAR");
        jLabel21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 130, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 970, 670));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, 10, 40));

        jbRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jbRegistrar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbRegistrar.setText("CERRAR SESIÓN");
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.setFocusable(false);
        jbRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(jbRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 640, 240, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 670, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 950, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbRegistrarMouseClicked

    private void jbAgregarProductoYusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAgregarProductoYusuariosMouseClicked
        frmAgregarProductoYusuario productoYusuario = new frmAgregarProductoYusuario();
        productoYusuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbAgregarProductoYusuariosMouseClicked

    private void jbListarProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbListarProductoMouseClicked
        frmListarProducto lp = new frmListarProducto();
        lp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbListarProductoMouseClicked

    private void jbListarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbListarUsuarioMouseClicked
        frmBuscarUsuario buscarUsuario = new frmBuscarUsuario();
        buscarUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbListarUsuarioMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        inhabilitar();
    }//GEN-LAST:event_formWindowOpened

    private void jbEstadisticaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbEstadisticaMouseClicked
        frmEstadisticasDeAlmacen eda = new frmEstadisticasDeAlmacen();
        eda.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbEstadisticaMouseClicked

    private void jbExportarPDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbExportarPDFMouseClicked
        frmExportarPDF exportarPDF = new frmExportarPDF();
        exportarPDF.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbExportarPDFMouseClicked

    private void jlabelDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelDBMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlabelDBMouseClicked

    private void jbtnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDesconectarActionPerformed
        inhabilitar();
    }//GEN-LAST:event_jbtnDesconectarActionPerformed

    private void jbtnConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConectarActionPerformed
        habilitar();
    }//GEN-LAST:event_jbtnConectarActionPerformed

    private void jbtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnActualizarActionPerformed
        actualizarTodasLasTablas();
    }//GEN-LAST:event_jbtnActualizarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        eliminarTodasLasTablas();
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbDatosEmpresarialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbDatosEmpresarialMouseClicked
        frmEstadisticaEmpresariales ee = new frmEstadisticaEmpresariales();
        ee.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbDatosEmpresarialMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//        actualizarTodasLasTablas();
    }//GEN-LAST:event_formWindowClosed

    private void jlabelArbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabelArbolMouseClicked
        frmListarArbol la = new frmListarArbol();
        la.setVisible(true);
        dispose();
    }//GEN-LAST:event_jlabelArbolMouseClicked

    private void actualizarTodasLasTablas(){
        eliminarTodasLasTablas();
        agregarUsariosBD();
        agregarEmpleadoBD();
        agregarProductoBD();
    }
    
    private void agregarUsariosBD() {
        Iterator<Usuario> itUsuario = listaUsuario.iterator();
        try {

            Conexion conexion = new Conexion();
            Connection connection = conexion.getConnection();
            PreparedStatement ps = connection.prepareStatement(
                    "insert into usuarios (codigo, nombre, telefono) values (?,?,?)"
            );
            int resultado = 0;
            while (itUsuario.hasNext()) {
                Usuario u = itUsuario.next();
                ps.setString(1, u.getCodigo());
                ps.setString(2, u.getNombre());
                ps.setLong(3, u.getTelefono());
                resultado = ps.executeUpdate();
            }
            if (resultado > 0) {
                System.out.println("SE EJECUTO CORRECTO");
            } else {
                System.out.println("NO SE EJECUTO CORRECTO");
            }
            connection.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }

    }

    private void agregarEmpleadoBD() {
        Conexion conexion = new Conexion();
        Connection connection = conexion.getConnection();
        Iterator<Empleado> itEmpleado = listaEmpleado.iterator();
        try {
            PreparedStatement ps = connection.prepareStatement(
                    "insert into empleado (nombre, correo, contraseña) values (?,?,?)"
            );
            while (itEmpleado.hasNext()) {
                Empleado e = itEmpleado.next();
                ps.setString(1, e.getNombre().toUpperCase());
                ps.setString(2, e.getCorreo());
                ps.setString(3, "*************");
                ps.executeUpdate();
            }
            connection.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void agregarProductoBD() {
        Conexion conexion = new Conexion();
        Connection connection = conexion.getConnection();
        Iterator<Producto> itProducto = listaProducto.iterator();
        int contador = 0;
//        DecimalFormat df = new DecimalFormat("####.00");
        try {

            PreparedStatement ps = connection.prepareStatement(
                    "INSERT INTO `productos`(`id`,`CODIGO DE PRODUCTO`, "
                    + "`ESTADO`, `CANTIDAD`, `CATEGORIA`, `NOMBRE`, "
                    + "`PRECIO UNITARIO`, `ALMACEN`, `DESTINO`, "
                    + "`FECHA DE REGISTRO`, `FECHA DE ENTREGA`, "
                    + "`CODIGO DE USUARIO`, `PRECIO TOTAL`) "
                    + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)"
            );
            while (itProducto.hasNext()) {
                contador++;
                Producto p = itProducto.next();
                ps.setInt(1, contador);
                ps.setString(2, p.getCodigoDeProducto());
                ps.setString(3, p.getEstado());
                ps.setInt(4, p.getCantidad());
                ps.setString(5, p.getCategoria());
                ps.setString(6, p.getNombreDeProducto());
                ps.setDouble(7, p.getPrecioUnitario());
                ps.setString(8, p.getAlmacen());
                ps.setString(9, p.getDestino());
                ps.setString(10, p.getFechaDeRegistro());
                ps.setString(11, p.getFechaProgramadaDeEntrega());
                ps.setString(12, p.getCodigoDeUsuario());
                ps.setDouble(13, p.calcularPrecioDeUnTipoDeProducto());
                ps.executeUpdate();
            }
            connection.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void eliminarTodasLasTablas() {
        eliminarTablas("usuarios");
        eliminarTablas("productos");
        eliminarTablas("empleado");
    }

    private void eliminarTablas(String nombreTabla) {
        Conexion conexion = new Conexion();
        Connection connection = conexion.getConnection();
        try {
            PreparedStatement ps = connection.prepareStatement(
                    "delete from " + nombreTabla
            );
            ps.executeUpdate();
            connection.close();
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
    }

    private void habilitar() {
        jbtnConectar.setEnabled(false);
        jbtnActualizar.setEnabled(true);
        jbtnDesconectar.setEnabled(true);
        jbtnEliminar.setEnabled(true);
    }

    private void inhabilitar() {
        jbtnConectar.setEnabled(true);
        jbtnActualizar.setEnabled(false);
        jbtnDesconectar.setEnabled(false);
        jbtnEliminar.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jbAgregarProductoYusuarios;
    private javax.swing.JLabel jbDatosEmpresarial;
    private javax.swing.JLabel jbEstadistica;
    private javax.swing.JLabel jbExportarPDF;
    private javax.swing.JLabel jbListarProducto;
    private javax.swing.JLabel jbListarUsuario;
    private javax.swing.JLabel jbLogoDeEntrada;
    private javax.swing.JLabel jbRegistrar;
    private javax.swing.JButton jbtnActualizar;
    private javax.swing.JButton jbtnConectar;
    private javax.swing.JButton jbtnDesconectar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JLabel jlabelArbol;
    private javax.swing.JLabel jlabelDB;
    // End of variables declaration//GEN-END:variables
}
