/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import Clases.OperacionesData;
import Controladores.ControladorData;
import Controladores.ControladorDeGraficas;

public class frmListarProducto extends javax.swing.JFrame {

    private DefaultTableModel dtmTablaDeProductos;
    private DefaultTableModel dtmTablaDeUsuarios;
    Object[][] data = {};
    String headerProducto[] = {"CODIGO DE PRODUCTO", "ESTADO", "CANTIDAD", "CATEGORIA", "NOMBRE DE PRODUCTO", "PRECIO UNITARIO",
        "ALMACEN", "DESTINO", "FECHA DE REGISTRO", "FECHA DE ENTREGA", "CODIGO DE USUARIO", "PRECIO TOTAL"
    };
    String headerUsuario[] = {"CODIGO DE USUARIO", "NOMBRE DE USUARIO", "TELEFONO"};
//    OperacionesData od;
    ControladorData cd;
    ControladorDeGraficas controladorDeGraficas = new ControladorDeGraficas();

    public frmListarProducto() {
        initComponents();
        /*TBL DE PRODUCTO*/
        dtmTablaDeProductos = new DefaultTableModel();
        dtmTablaDeProductos.setDataVector(data, headerProducto);
        jtblProductos.setModel(dtmTablaDeProductos);
        /*TBL DE USUARIOS*/
        dtmTablaDeUsuarios = new DefaultTableModel();
        dtmTablaDeUsuarios.setDataVector(data, headerUsuario);
        jtblUsuarios.setModel(dtmTablaDeUsuarios);
        /*OPERACIONES EXTRA*/
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        cd = new ControladorData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrientacion = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnInicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        jpanelBarraDeEstados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblUsuarios = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jtxtCantidadDeUsuarios = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jtxtCantidadDeProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrbFinInicio = new javax.swing.JRadioButton();
        jcbProducto = new javax.swing.JCheckBox();
        jcbUsuario = new javax.swing.JCheckBox();
        jrbInicioFIn = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LISTAR PRODUCTOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 40));

        jbtnInicio.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, 300, 60));

        jtblProductos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO DE PRODUCTO", "ESTADO", "CANTIDAD", "CATEGORIA", "NOMBRE DE PRODUCTO", "PRECIO UNITARIO", "ALMACEN", "DESTINO", "FECHA DE REGISTRO", "FECHA DE ENTREGA", "NOMBRE DE USUARIO", "PRECIO TOTAL"
            }
        ));
        jtblProductos.setRowHeight(30);
        jScrollPane1.setViewportView(jtblProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1290, 270));

        jpanelBarraDeEstados.setBackground(new java.awt.Color(215, 215, 215));
        jpanelBarraDeEstados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpanelBarraDeEstadosLayout = new javax.swing.GroupLayout(jpanelBarraDeEstados);
        jpanelBarraDeEstados.setLayout(jpanelBarraDeEstadosLayout);
        jpanelBarraDeEstadosLayout.setHorizontalGroup(
            jpanelBarraDeEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );
        jpanelBarraDeEstadosLayout.setVerticalGroup(
            jpanelBarraDeEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jPanel2.add(jpanelBarraDeEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 520, 300));

        jtblUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblUsuarios.setRowHeight(30);
        jScrollPane2.setViewportView(jtblUsuarios);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 740, 240));

        jPanel7.setBackground(new java.awt.Color(215, 215, 215));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CANTIDAD DE USUARIOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCantidadDeUsuarios.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCantidadDeUsuarios.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCantidadDeUsuarios.setBorder(null);
        jPanel7.add(jtxtCantidadDeUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 40));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 370, 70));

        jPanel6.setBackground(new java.awt.Color(215, 215, 215));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CANTIDAD DE PRODUCTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Semilight", 0, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCantidadDeProducto.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCantidadDeProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCantidadDeProducto.setBorder(null);
        jPanel6.add(jtxtCantidadDeProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 230, 40));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 580, 370, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ORIENTACIÓN DE LA INFORMACIÓN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 540, 30));

        grupoOrientacion.add(jrbFinInicio);
        jrbFinInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbFinInicio.setText("Fin a Inicio");
        jrbFinInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbFinInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFinInicioMouseClicked(evt);
            }
        });
        jPanel2.add(jrbFinInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 700, 120, -1));

        jcbProducto.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbProducto.setText("Producto");
        jcbProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jcbProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 700, 120, -1));

        jcbUsuario.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jcbUsuario.setText("Usuario");
        jcbUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jcbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, 120, -1));

        grupoOrientacion.add(jrbInicioFIn);
        jrbInicioFIn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbInicioFIn.setText("Inicio a Fin");
        jrbInicioFIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbInicioFIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbInicioFInMouseClicked(evt);
            }
        });
        jPanel2.add(jrbInicioFIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 120, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 1330, 750));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 710, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 720, 270, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 990, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1330, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        frmInicio inicio = new frmInicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jrbFinInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFinInicioMouseClicked
        if (!jcbProducto.isSelected() && !jcbUsuario.isSelected() || jcbProducto.isSelected() && jcbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosFinInicio(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosFinInicio(dtmTablaDeUsuarios);
        }
        if (jcbProducto.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosFinInicio(dtmTablaDeProductos);
        }
        if (jcbUsuario.isSelected()) {
            cd.sobreEscribirTablaDeUsuariosFinInicio(dtmTablaDeUsuarios);
        }
    }//GEN-LAST:event_jrbFinInicioMouseClicked

    private void jrbInicioFInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbInicioFInMouseClicked
        if (!jcbProducto.isSelected() && !jcbUsuario.isSelected() || jcbProducto.isSelected() && jcbUsuario.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
            cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        }
        if (jcbProducto.isSelected()) {
            cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        }
        if (jcbUsuario.isSelected()) {
            cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        }
    }//GEN-LAST:event_jrbInicioFInMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        mostrarValores();
    }//GEN-LAST:event_formWindowOpened

    private void mostrarValores() {
        cd.sobreEscribirEnTablaDeProductosInicioFin(dtmTablaDeProductos);
        cd.sobreEscribirTablaDeUsuariosInicioFin(dtmTablaDeUsuarios);
        jtxtCantidadDeProducto.setText(String.valueOf(dtmTablaDeProductos.getRowCount()) + " producto");
        jtxtCantidadDeUsuarios.setText(String.valueOf(dtmTablaDeUsuarios.getRowCount()) + " usuarios");
        controladorDeGraficas.graficarBarrasDeEstado(jpanelBarraDeEstados);
        jcbProducto.setSelected(true);
        jcbUsuario.setSelected(true);
        jrbInicioFIn.setSelected(true);
        pack();
        repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoOrientacion;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JCheckBox jcbProducto;
    private javax.swing.JCheckBox jcbUsuario;
    private javax.swing.JPanel jpanelBarraDeEstados;
    private javax.swing.JRadioButton jrbFinInicio;
    private javax.swing.JRadioButton jrbInicioFIn;
    private javax.swing.JTable jtblProductos;
    private javax.swing.JTable jtblUsuarios;
    private javax.swing.JTextField jtxtCantidadDeProducto;
    private javax.swing.JTextField jtxtCantidadDeUsuarios;
    // End of variables declaration//GEN-END:variables
}
