/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.Color;
import Clases.OperacionesData;
import Controladores.PlaceHolder;

public class frmLogueo extends javax.swing.JFrame {

    private OperacionesData operacionesData;
    
    public frmLogueo() {
        initComponents();
        frmLogueo.this.setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        operacionesData = new OperacionesData();
        establecerPlaceHolders();
    }
    
    private void establecerPlaceHolders(){
        PlaceHolder phCorreo = new PlaceHolder("Ingresar el correo electronico", jtxtCorreoDelEmpleado);
        PlaceHolder phContrasena = new PlaceHolder("Ingresar la contraseña", jtxtContrasenaDelEmpleado);
        PlaceHolder phNombre = new PlaceHolder("Ingresar el nombre del empleado", jtxtNombreDelEmpleado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtContrasenaDelEmpleado = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jtxtNombreDelEmpleado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jtxtCorreoDelEmpleado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jbtnLoguear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbRegistrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGUEO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 63));

        jPanel3.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtContrasenaDelEmpleado.setBackground(new java.awt.Color(215, 215, 215));
        jtxtContrasenaDelEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtContrasenaDelEmpleado.setBorder(null);
        jtxtContrasenaDelEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtContrasenaDelEmpleadoActionPerformed(evt);
            }
        });
        jPanel3.add(jtxtContrasenaDelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 390, 70));

        jPanel4.setBackground(new java.awt.Color(215, 215, 215));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtNombreDelEmpleado.setBackground(new java.awt.Color(215, 215, 215));
        jtxtNombreDelEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtNombreDelEmpleado.setBorder(null);
        jPanel4.add(jtxtNombreDelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 50));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 390, 70));

        jPanel5.setBackground(new java.awt.Color(215, 215, 215));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtCorreoDelEmpleado.setBackground(new java.awt.Color(215, 215, 215));
        jtxtCorreoDelEmpleado.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxtCorreoDelEmpleado.setBorder(null);
        jPanel5.add(jtxtCorreoDelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 310, 50));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 390, 70));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEGUIMIENTO DE PRODUCTO RENZO COSTA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 530, 63));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 50, 40));

        jbtnLoguear.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLoguear.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnLoguear.setText("LOGUEAR");
        jbtnLoguear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLoguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoguearActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLoguear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 530, 490));

        jPanel2.setBackground(new java.awt.Color(149, 16, 43));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jbRegistrar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jbRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbRegistrar.setText("REGISTRAR");
        jbRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbRegistrar.setFocusable(false);
        jbRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbRegistrarMouseClicked(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(356, 356, 356))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 630, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbRegistrarMouseClicked
        frmRegistro registro = new frmRegistro();
        registro.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbRegistrarMouseClicked

    private void jtxtContrasenaDelEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtContrasenaDelEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtContrasenaDelEmpleadoActionPerformed

    private void jbtnLoguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoguearActionPerformed
        if(operacionesData.validarEmpleado(jtxtNombreDelEmpleado.getText(), jtxtCorreoDelEmpleado.getText(), jtxtContrasenaDelEmpleado.getText())){
            frmInicio inicio = new frmInicio();
            inicio.setVisible(true);
            dispose();
        }
        limpiarCasillas();
    }//GEN-LAST:event_jbtnLoguearActionPerformed

    private void limpiarCasillas() {
        jtxtContrasenaDelEmpleado.setText("");
        jtxtCorreoDelEmpleado.setText("");
        jtxtNombreDelEmpleado.setText("");
        jtxtNombreDelEmpleado.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbRegistrar;
    private javax.swing.JButton jbtnLoguear;
    private javax.swing.JPasswordField jtxtContrasenaDelEmpleado;
    private javax.swing.JTextField jtxtCorreoDelEmpleado;
    private javax.swing.JTextField jtxtNombreDelEmpleado;
    // End of variables declaration//GEN-END:variables
}
