/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Producto;
import Controladores.ControladorData;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.TreeSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yanni
 */
public class frmListarArbol extends javax.swing.JFrame {

    ControladorData cd;
    LinkedList<Producto> listaProducto;
    TreeSet<Producto> arbolProducto;
    DefaultTableModel dtmTabla;

    public frmListarArbol() {
        initComponents();

        definirTabla();
        cd = new ControladorData();
        listaProducto = cd.instanciarListaProducto();

        arbolProducto = instanciarArbol(0);
        sobreEscribirEnTablaDeProductos();

        /*op diseño*/
        jrbCodigo.setSelected(true);
        setBackground(new Color(0, 0, 0, 0));
        setLocationRelativeTo(null);
    }

    private void definirTabla() {
        String headerProducto[] = {"CODIGO DE PRODUCTO", "ESTADO", "CANTIDAD", "CATEGORIA", "NOMBRE DE PRODUCTO", "PRECIO UNITARIO",
            "ALMACEN", "DESTINO", "FECHA DE REGISTRO", "FECHA DE ENTREGA", "CODIGO DE USUARIO", "PRECIO TOTAL"
        };
        Object[][] data = {};
        dtmTabla = new DefaultTableModel(data, headerProducto);
        jtblProductos.setModel(dtmTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOrden = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtnInicio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProductos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jrbNombre = new javax.swing.JRadioButton();
        jrbCodigo = new javax.swing.JRadioButton();
        jrbPrecioTotal = new javax.swing.JRadioButton();
        jrbCantidad = new javax.swing.JRadioButton();
        jrbFechaRegistro = new javax.swing.JRadioButton();
        jrbFechaEntrega = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LISTAR PRODUCTOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 40));

        jbtnInicio.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 670, 300, 60));

        jtblProductos.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO DE PRODUCTO", "ESTADO", "CANTIDAD", "CATEGORIA", "NOMBRE DE PRODUCTO", "PRECIO UNITARIO", "ALMACEN", "DESTINO", "FECHA DE REGISTRO", "FECHA DE ENTREGA", "NOMBRE DE USUARIO", "PRECIO TOTAL"
            }
        ));
        jtblProductos.setRowHeight(30);
        jScrollPane1.setViewportView(jtblProductos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1290, 590));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ORDENAR EN FUNCIÓN AL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 670, 860, 30));

        grupoOrden.add(jrbNombre);
        jrbNombre.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbNombre.setText("Nombre");
        jrbNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbNombreMouseClicked(evt);
            }
        });
        jPanel2.add(jrbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, 120, -1));

        grupoOrden.add(jrbCodigo);
        jrbCodigo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbCodigo.setText("Codigo");
        jrbCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbCodigoMouseClicked(evt);
            }
        });
        jPanel2.add(jrbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 120, -1));

        grupoOrden.add(jrbPrecioTotal);
        jrbPrecioTotal.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbPrecioTotal.setText("Precio Final");
        jrbPrecioTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbPrecioTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPrecioTotalMouseClicked(evt);
            }
        });
        jPanel2.add(jrbPrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 700, 120, -1));

        grupoOrden.add(jrbCantidad);
        jrbCantidad.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbCantidad.setText("Cantidad");
        jrbCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbCantidadMouseClicked(evt);
            }
        });
        jPanel2.add(jrbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 700, 120, -1));

        grupoOrden.add(jrbFechaRegistro);
        jrbFechaRegistro.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbFechaRegistro.setText("Fecha Registro");
        jrbFechaRegistro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbFechaRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFechaRegistroMouseClicked(evt);
            }
        });
        jPanel2.add(jrbFechaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 140, -1));

        grupoOrden.add(jrbFechaEntrega);
        jrbFechaEntrega.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jrbFechaEntrega.setText("Fecha Entrega");
        jrbFechaEntrega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbFechaEntrega.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFechaEntregaMouseClicked(evt);
            }
        });
        jPanel2.add(jrbFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 1330, 750));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 710, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 720, 270, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 990, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 1330, 760));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        frmInicio inicio = new frmInicio();
        inicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jrbNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbNombreMouseClicked
        if (jrbNombre.isSelected()) {
            arbolProducto = instanciarArbol(1);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbNombreMouseClicked

    private void jrbCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbCodigoMouseClicked
        if (jrbCodigo.isSelected()) {
            arbolProducto = instanciarArbol(0);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbCodigoMouseClicked

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jrbPrecioTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPrecioTotalMouseClicked
        if (jrbPrecioTotal.isSelected()) {
            arbolProducto = instanciarArbol(3);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbPrecioTotalMouseClicked

    private void jrbCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbCantidadMouseClicked
        if (jrbCantidad.isSelected()) {
            arbolProducto = instanciarArbol(2);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbCantidadMouseClicked

    private void jrbFechaRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFechaRegistroMouseClicked
        if (jrbFechaRegistro.isSelected()) {
            arbolProducto = instanciarArbol(4);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbFechaRegistroMouseClicked

    private void jrbFechaEntregaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFechaEntregaMouseClicked
        if (jrbFechaEntrega.isSelected()) {
            arbolProducto = instanciarArbol(5);
            sobreEscribirEnTablaDeProductos();
        }
    }//GEN-LAST:event_jrbFechaEntregaMouseClicked

    private TreeSet<Producto> instanciarArbol(int indice) {
        boolean[] comparacion = new boolean[6];
        for (int i = 0; i < comparacion.length; i++) {
            comparacion[i] = false;
        }
        comparacion[indice] = true;
        Producto.setComparacion(comparacion);
        TreeSet<Producto> arbolTemporal = new TreeSet<>();
        Iterator<Producto> itProducto = listaProducto.iterator();
        while (itProducto.hasNext()) {
            arbolTemporal.add(itProducto.next());
        }
        return arbolTemporal;
    }

    private void sobreEscribirEnTablaDeProductos() {
        dtmTabla.setRowCount(0);//VACIAMOS LA TABLA
        DecimalFormat dfProducto = new DecimalFormat("#.00");
        Iterator<Producto> it = arbolProducto.iterator();
        while (it.hasNext()) {
            Producto p = it.next();
            Object[] filaProducto = {p.getCodigoDeProducto(), p.getEstado(), p.getCantidad(), p.getCategoria(),
                p.getNombreDeProducto(), dfProducto.format(p.getPrecioUnitario()), p.getAlmacen(), p.getDestino(), p.getFechaDeRegistro(),
                p.getFechaProgramadaDeEntrega(), p.getCodigoDeUsuario(), dfProducto.format(p.calcularPrecioDeUnTipoDeProducto())
            };
            dtmTabla.addRow(filaProducto);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoOrden;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JRadioButton jrbCantidad;
    private javax.swing.JRadioButton jrbCodigo;
    private javax.swing.JRadioButton jrbFechaEntrega;
    private javax.swing.JRadioButton jrbFechaRegistro;
    private javax.swing.JRadioButton jrbNombre;
    private javax.swing.JRadioButton jrbPrecioTotal;
    private javax.swing.JTable jtblProductos;
    // End of variables declaration//GEN-END:variables
}
