/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Clases.Producto;
import Controladores.ControladorData;
import java.awt.Color;
import java.awt.Frame;
import java.util.LinkedList;
import java.util.ListIterator;

public class jdBoleta extends javax.swing.JDialog {

    Frame frame;

    public jdBoleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        frame = parent;
        initComponents();

        setTitle("BOLETA DEL CLIENTE");
        setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtnInicio = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Consultar = new javax.swing.JButton();
        jbtnInicio1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxaBoleta = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jbCerrarSesion = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnInicio.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 230, 60));

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jbSalir.setText("X");
        jbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel2.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 50, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BOLETA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 60));

        Consultar.setBackground(new java.awt.Color(149, 16, 43));
        Consultar.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        Consultar.setForeground(new java.awt.Color(255, 255, 255));
        Consultar.setText("IMPRIMIR");
        Consultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarActionPerformed(evt);
            }
        });
        jPanel2.add(Consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 210, 60));

        jbtnInicio1.setBackground(new java.awt.Color(149, 16, 43));
        jbtnInicio1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jbtnInicio1.setForeground(new java.awt.Color(255, 255, 255));
        jbtnInicio1.setText("CERRAR");
        jbtnInicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicio1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 230, 60));

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jtxaBoleta.setColumns(20);
        jtxaBoleta.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 18)); // NOI18N
        jtxaBoleta.setRows(5);
        jScrollPane1.setViewportView(jtxaBoleta);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, 820, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 880, 590));

        jPanel1.setBackground(new java.awt.Color(149, 16, 43));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 40, 40));

        jbCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jbCerrarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jbCerrarSesion.setText("CERRAR SESIÓN");
        jbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbCerrarSesion.setFocusable(false);
        jbCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbCerrarSesionMouseClicked(evt);
            }
        });
        jPanel1.add(jbCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RENZO COSTA S.A.C.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 540, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 880, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCerrarSesionMouseClicked
        frame.dispose();
        dispose();
        frmLogueo logueo = new frmLogueo();
        logueo.setVisible(true);
    }//GEN-LAST:event_jbCerrarSesionMouseClicked

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        frmInicio i = new frmInicio();
        i.setVisible(true);
        frame.dispose();
        dispose();
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarActionPerformed
    }//GEN-LAST:event_ConsultarActionPerformed

    private void jbtnInicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicio1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnInicio1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Producto p = getLastProduct();
        writeTextArea(p);
    }//GEN-LAST:event_formWindowOpened

    public void writeTextArea(Producto p) {
        jtxaBoleta.append("\t\t\tttRENZO COSTA S.A.C. PRODUCTOS\n");
        jtxaBoleta.append("=========================================================================\n");
        jtxaBoleta.append("\t\t\tBOLETA\n");
        jtxaBoleta.append("=========================================================================\n");
        jtxaBoleta.append("CODIGO DEL PRODUCTO\t\t: " + p.getCodigoDeProducto().toUpperCase() + "\n");
        jtxaBoleta.append("ESTADO DEL PRODUCTO\t\t: " + p.getEstado().toUpperCase() + "\n");
        jtxaBoleta.append("CANTIDAD DEL PRODUCTO\t\t: " + p.getCantidad() + "\n");
        jtxaBoleta.append("CATEGORIA DEL PRODUCTO\t\t: " + p.getCategoria().toUpperCase() + "\n");
        jtxaBoleta.append("NOMBRE DEL PRODUCTO\t\t: " + p.getNombreDeProducto().toUpperCase() + "\n");
        jtxaBoleta.append("PRECIO UNITARIO DEL PRODUCTO\t: " + p.getPrecioUnitario() + "\n");
        jtxaBoleta.append("PRECIO TOTAL DEL PRODUCTO\t: " + p.calcularPrecioDeUnTipoDeProducto() + "\n");
        jtxaBoleta.append("ALMACEN DEL PRODUCTO\t\t: " + p.getAlmacen().toUpperCase() + "\n");
        jtxaBoleta.append("DESTINO DEL PRODUCTO\t\t: " + p.getDestino() + "\n");
        jtxaBoleta.append("FECHA DE REGISTRO DEL PRODUCTO\t: " + p.getFechaDeRegistro() + "\n");
        jtxaBoleta.append("FECHA DE ENTREGA DEL PRODUCTO\t: " + p.getFechaProgramadaDeEntrega() + "\n");
        jtxaBoleta.append("CODIGO DE USUARIO DEL PRODUCTO\t: " + p.getCodigoDeUsuario().toUpperCase() + "\n");
        jtxaBoleta.append("=========================================================================\n");
    }

    private Producto getLastProduct() {
        Producto p = null;
        ControladorData cd = new ControladorData();
        LinkedList<Producto> lista = cd.instanciarListaProducto();
        ListIterator<Producto> it = lista.listIterator();
        while (it.hasNext()) {
            it.next();
        }
        while (it.hasPrevious()) {
            p = it.previous();
            return p;
        }
        return p;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jdBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jdBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jdBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jdBoleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jdBoleta dialog = new jdBoleta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Consultar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jbCerrarSesion;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnInicio1;
    private javax.swing.JTextArea jtxaBoleta;
    // End of variables declaration//GEN-END:variables
}
